/*

 SIMPLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : C:\Users\Rolemberg\Documents\ihsdungeons\gbtd-tileDesigner\backTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define simpleMapWidth 20
#define simpleMapHeight 36
#define simpleMapBank 0

extern unsigned char simpleMap[];

/* End of SIMPLEMAP.H */
