/*

 MINION.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0x08,0x08,0x3C,0x34,0x7C,0x44,0xFE,0xAA,
  0xFE,0x82,0xFE,0x82,0x7C,0x44,0x38,0x38,
  0x08,0x08,0x3C,0x34,0x7C,0x44,0xFE,0xAA,
  0xFE,0x92,0xFE,0xAA,0x7C,0x44,0x38,0x38
};

/* End of MINION.C */
